### ISSUE TITLE
Bad results with Rails

### ISSUE THREAD

**Issue by jscheid** [dryruby/json-canonicalization#2]
**Describe the bug**

Results don't always match the spec when using this gem with also the `rails` gem loaded (more precisely: the `activesupport` gem, which is a dependency of `rails`).

This is because Rails overrides a number of `to_json` methods and modifies them in a way that is incompatible, [for example](https://github.com/rails/rails/blob/8bdf5e35579c3211d2d6d7624d5167e0f673c3bd/activesupport/lib/active_support/json/encoding.rb#L42-L44).

**To reproduce**
1. Install and require this gem and `rails`
3. `"&".to_json_c14n` should give `"&"` but instead gives `"\u0026"`.

**Expected behavior**
This gem's behavior shouldn't depend on the presence of other gems, at least not ones as common as Rails.

**Comment by jscheid** [comment]
I believe the best fix here to be using `::JSON.generate(value)` instead of `value.to_json` everywhere.

**Comment by gkellogg** [comment]
Thanks for the PR. I’ll release an update shortly.

**Comment by jscheid** [comment]
Thanks, appreciate it.

**Comment by sumirolabs** [comment]
This should have been a breaking change. We have apps that use this gem on both sides of an API call to generate signatures and when one (and only one) side uses v 0.3.2 the signatures do not match. 

This seems like a good / proper update, but since the output has changed, I think this should have been flagged as a "breaking" change.

**Comment by gkellogg** [comment]
Can't quite see how the change from `#to_json` to `::JSON.generate()` would be a breaking change. Is there some remediation you'd like to see? Do you have a test case that can be added to illustrate the issue?

**Comment by sumirolabs** [comment]
As I understand this PR (and read the code), the goal was remove the changes that Rails may inject into how JSON is generated. This means that the previous versions of this gem could produce different output.

I'm thinking that because the output changed, the gem is no longer behaving exactly the same as before and thus any app that depended upon the previous behavior could now be "broken". 

I realize that this could also be considered a bugfix, but identifying this change as significant could have helped us detect that this new version of the gem is not compatible with older versions when used to generate signatures in our apps.

**Comment by gkellogg** [comment]
Well, we can always release the same code as 3.3.0 and pull the current version from RybyGems, if that would help.

my guess is that you are depending on something else that overloads `#to_json` that resulted in this dependency. You may be canonicalizing data that is not reduced to simple maps, arrays, numbers, strings and booleans.

**Comment by sumirolabs** [comment]
> my guess is that you are depending on something else that overloads #to_json that resulted in this dependency.

Yes, we are using this in a Rails app that overloads `to_json`, which is why this PR was made.

Anytime someone uses v0.3.2 and a previous version of `json-canonicalization` (in 2 separate apps), the output will be different because 0.3.2 will not include the Rails overrides while < 0.3.2 will include the Rails overrides - or am I missing something here?

My suggestion is to bump the version to 1.0.0 and add a `CHANGELOG.md` that describes how 0.3.2 / 1.0.0 differs from < 0.3.2.

**Comment by gkellogg** [comment]
I'll release a 1.0.0 based on the current 0.3.2. But, note that yanking 0.3.2 may break some dependencies as well.

We use the [GitHub release mechanism](https://github.com/dryruby/json-canonicalization/releases) in preference to a CHANGELOG.md file.

**Comment by gkellogg** [comment]
0.3.2 yanked and 1.0.0 released.

**Comment by renchap** [comment]
You should not have yanked the 0.3.0 version, this is breaking software depending on this version.

For example, Mastodon  (https://github.com/mastodon/mastodon/issues/28224). This requires us to release a new version as nobody can install a stable version of Mastodon 4.2 (4.2.0, 4.2.1 or 4.2.2) anymore.

Would it be possible to restore version 0.3.2?

**Comment by sumirolabs** [comment]
While I appreciate the version bump, I think yanking 0.3.2 probably wasn't the best idea.

**Comment by bbpennel** [comment]
Yes, thanks for working on this, unfortunately the new version requires ruby 3 while the yanked version required ruby 2.6, so this is causing dependency issues for us. I will most likely have to revert to 0.3.1

**Comment by defnull** [comment]
> This should have been a breaking change. We have apps that use this gem on both sides of an API call to generate signatures and when one (and only one) side uses v 0.3.2 the signatures do not match.

You could also argue that 0.3.1 was a buggy version and fixing a bug (restoring expected behavior) is not a breaking change. SemVer also defines `0.x` as unstable, expecting perfect backwards compatibility in a `0.3` release is a lot to ask.

**Comment by sumirolabs** [comment]
Agreed (I mentioned that above), this is a bit of a grey area. At the very least a `CHANGELOG.md` would have helped.

**Comment by renchap** [comment]
The issue here is that the buggy version has been released for multiple months. Yanking this (buggy) version broke `bundle install` for every project using this version in their `Gemfile.lock`. This has a huge impact on many software projects, broke all the CIs, and for projects like us (Mastodon) who are releasing open-source software and required an emergency update.

Yanking a gem should only happen when there is a security issue with this specific version, and be done carefuly if your gem is used by other projects.

**Comment by gkellogg** [comment]
Obviously no good solution here. Can't restore 0.3.2, but could release a 0.3.3 which again uses the `#to_json` and runs on Ruby 2.7+.

I did what was asked, (see https://github.com/dryruby/json-canonicalization/issues/2#issuecomment-1839402748) and 0.3.2 did arguably break things that it shouldn't have. Also note that this is a sole-maintained project with no one else jumping in to help (true for many open source projects). Anyone that's unhappy with how it's managed can feel free to copy the implementation entirely,, as it uses the UNLICENCE and is completely in the public domain. I would also welcome additional maintainers, as a process being reviewed by others would help for this and numerous other gems I maintain.

Options you can weigh in on:

* [ ] release 0.3.3 as a duplicate of 0.3.1,
* [ ] release 0.4.0 as a duplicate of 0.3.3 with support for Ruby 2.7
* [ ] do nothing more and live with the changes.

**Comment by gkellogg** [comment]
> Agreed (I mentioned that above), this is a bit of a grey area. At the very least a `CHANGELOG.md` would have helped.

As mentioned above, my practice is to use [GitHub releases](https://github.com/dryruby/json-canonicalization/releases) as the change log.

**Comment by sumirolabs** [comment]
I definitely appreciate the sole-proprietor nature here, no complaints. I'll let others weigh in on the path forward from here.

**Comment by jscheid** [comment]
> Yanking this (buggy) version 

There must be a misunderstanding - 0.3.2 wasn't buggy - it fixed a bug.  I'm the one who opened this issue originally, and the PR in question, and I stand by it as a good improvement.

The change was yanked (for better or worse) not because there was anything wrong with it - only for considerations around how it should be versioned.

I wasn't involved in choosing which version to release it under, or in the decision to yank 0.3.2, but I'm sure @gkellogg only had best intentions and so did @sumirolabs, who presumably had already solved their own problem when they raised the versioning issue.

Let's use this incident to reflect on how we might want our package managers to work, and what guidance we should provide to package maintainers.  For a start, should [this](https://guides.rubygems.org/removing-a-published-gem/) perhaps not cheerfully say "here's how you can fix it" but rather "think twice before doing this"? There must be ways to limit the blast radius of versioning decisions and reduce pressure on individual maintainers.

As for which version to release next, I don't have a strong opinion.

**Comment by gkellogg** [comment]
See PR #4 and #5. This creates a 0.3.3 release which is basically the same as 0.3.1 including support for Ruby >= 2.6. And 0.4.0, which is the old 0.3.2 and now 1.0.0, but also with support for Ruby >= 2.6. 1.0.0 and future work is on Ruby >= 3.0.

If people are "happy" with this, I'll push these out as gem versions. Sorry that RubyGems does not allow re-releasing a yanked gem version.

**Comment by sumirolabs** [comment]
This seems sensible to me.

**Comment by gkellogg** [comment]
Release 0.3.3 and 0.4.0 pushed to RubyGems as discussed.
